function eventLinkRow(l={}){return `<div class="form-grid" data-event-link-row style="margin-bottom:8px"><label class="field"><span>Titre du lien</span><input data-event-link-label value="${esc(l.label||'')}"></label><label class="field"><span>URL</span><input data-event-link-url type="url" value="${esc(l.url||'')}"></label><button type="button" class="btn small danger" onclick="this.parentElement.remove()">Supprimer</button></div>`}

showDayEventForm=function(dayKey,eventId=null){
  const c=selected(),e=eventId?state.events.find(x=>x.id===eventId):null,target=document.getElementById('dayEventForm');if(!target)return;
  if(e&&!Array.isArray(e.links))e.links=[];
  target.innerHTML=`<div class="notice" style="margin-bottom:14px"><div class="form-grid"><label class="field"><span>Heure</span><input id="evtTime" type="time" value="${esc(e?.time||'')}"></label><label class="field"><span>Visible pour</span><select id="evtGroup">${groupOptions(e?.audience||'all')}</select></label><label class="field full"><span>Titre</span><input id="evtTitle" value="${esc(e?.title||'')}"></label><label class="field full"><span>Description</span><textarea id="evtDesc">${esc(e?.description||'')}</textarea></label></div><h4>Liens du rendez-vous</h4><div id="eventLinks">${(e?.links||[]).map(eventLinkRow).join('')}</div><button class="btn small" id="addEventLink">+ Ajouter un lien</button><h4>Contenus associés</h4>${typeof contentChecks==='function'?contentChecks(e?.contentIds||[],'evtContent'):''}<div class="actions" style="margin-top:10px"><button class="btn small" id="createEventContent">+ Créer un contenu</button></div><div id="eventInlineContent"></div><div class="actions" style="margin-top:14px"><button class="btn primary" id="saveEventBtn">${e?'Enregistrer':'Ajouter'}</button><button class="btn" onclick="document.getElementById('dayEventForm').innerHTML=''">Annuler</button></div></div>`;
  addEventLink.onclick=()=>eventLinks.insertAdjacentHTML('beforeend',eventLinkRow());
  createEventContent.onclick=()=>renderInlineContentCreator('eventInlineContent',id=>{const ids=[...document.querySelectorAll('input[name=evtContent]:checked')].map(x=>+x.value);ids.push(id);saveEventWithLinks(e,c,dayKey,[...new Set(ids)])});
  saveEventBtn.onclick=()=>{const title=evtTitle.value.trim();if(!title)return toast('Indiquez un titre');saveEventWithLinks(e,c,dayKey,[...document.querySelectorAll('input[name=evtContent]:checked')].map(x=>+x.value))};
};

function saveEventWithLinks(e,c,dayKey,contentIds){
  const links=[...document.querySelectorAll('[data-event-link-row]')].map(r=>({label:r.querySelector('[data-event-link-label]').value.trim(),url:r.querySelector('[data-event-link-url]').value.trim()})).filter(x=>x.url);
  const data={celebrationId:c.id,dayKey,time:evtTime.value,title:evtTitle.value.trim()||'Rendez-vous',audience:evtGroup.value,description:evtDesc.value,links,contentIds};
  if(e)Object.assign(e,data);else state.events.push({id:Date.now(),...data});saveState(state);editDay(dayKey);toast('Rendez-vous enregistré');
}

editDay=function(key){
  const c=selected(),d=c.days.find(x=>x.key===key);if(!d)return renderProgram();
  if(!Array.isArray(d.links))d.links=[];
  const events=state.events.filter(e=>e.celebrationId===c.id&&e.dayKey===key).sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));
  const dateFields=d.label==='Préparation'?`<label class="field"><span>Date de début</span><input id="dStart" type="date" value="${esc(d.startDate||'')}"></label><label class="field"><span>Date de fin</span><input id="dEnd" type="date" value="${esc(d.endDate||'')}"></label>`:d.label==='Après célébration'?'':`<label class="field"><span>Date</span><input id="dStart" type="date" value="${esc(d.startDate||'')}"></label>`;
  panel.innerHTML=`${context()}<div class="card"><div class="eyebrow">${esc(d.label)}</div><h2>${esc(d.label)}</h2><div class="form-grid">${dateFields}<label class="field full"><span>Texte</span><textarea id="dText">${esc(d.text||'')}</textarea></label></div><h3>Contenus</h3><div id="dayContentActions"></div><div class="actions" style="margin-top:10px"><button class="btn small" id="createDayContent">+ Créer un contenu</button></div><div id="dayInlineContent"></div><div class="actions" style="margin-top:18px"><button class="btn primary" id="saveDay">Enregistrer</button><button class="btn" onclick="renderProgram()">Retour</button></div></div><div class="card section"><div class="section-head"><h2 style="margin:0">Rendez-vous</h2><button class="btn primary" onclick="showDayEventForm('${key}')">+ Ajouter un rendez-vous</button></div><div id="dayEventForm"></div><div class="list">${events.length?events.map(eventRow).join(''):'<div class="notice">Aucun rendez-vous.</div>'}</div></div><div class="card section"><h2>Autres liens du jour</h2><div id="dayLinks">${d.links.map((l,i)=>linkRow(l,i)).join('')}</div><button class="btn small" id="addLink">+ Ajouter un lien</button><div class="actions" style="margin-top:14px"><button class="btn primary" id="saveLinks">Enregistrer les liens</button></div></div>`;
  if(typeof renderDayContentActions==='function')renderDayContentActions(d,key);else dayContentActions.innerHTML=typeof contentChecks==='function'?contentChecks(d.contentIds||[],'dayContent'):'';
  createDayContent.onclick=()=>renderInlineContentCreator('dayInlineContent',id=>{d.contentIds=[...new Set([...(d.contentIds||[]),id])];saveState(state);editDay(key)});
  addLink.onclick=()=>dayLinks.insertAdjacentHTML('beforeend',linkRow({label:'',url:''},dayLinks.children.length));
  saveDay.onclick=()=>{if(d.label==='Préparation'){const s=dStart.value,e=dEnd.value||s;if(s&&e&&e<s)return toast('La date de fin doit suivre la date de début');d.startDate=s;d.endDate=e}else if(d.label==='Après célébration'){d.startDate='';d.endDate=''}else{const s=dStart.value;d.startDate=s;d.endDate=s}d.text=dText.value;saveState(state);editDay(key);toast('Enregistré')};
  saveLinks.onclick=()=>{d.links=[...dayLinks.querySelectorAll('[data-link-row]')].map(r=>({label:r.querySelector('[data-link-label]').value.trim(),url:r.querySelector('[data-link-url]').value.trim()})).filter(x=>x.url);saveState(state);editDay(key);toast('Liens enregistrés')};
};
