const ARCHANGELS={Michaël:'#b42318',Gabriel:'#173b70',Raphaël:'#16803c',Ouriel:'#d39e00'};
const DEFAULTS={version:6,currentCelebrationId:101,adminCelebrationId:101,profile:'all',groups:[{id:'all',name:'Tous'},{id:'angel',name:"Porteurs d’Ange"},{id:'nonangel',name:"Non-porteurs d’Ange"}],categories:['Audio','Textes','Vidéos','PDF','Images','Liens'],celebrations:[
{id:101,archangel:'Michaël',year:'2026',status:'active',days:[{key:'preparation',label:'Préparation',startDate:'',endDate:'',text:'',links:[]},{key:'2026-09-16',label:'Mercredi',startDate:'2026-09-16',endDate:'2026-09-16',text:'',links:[]},{key:'2026-09-17',label:'Jeudi',startDate:'2026-09-17',endDate:'2026-09-17',text:'',links:[]},{key:'2026-09-18',label:'Vendredi',startDate:'2026-09-18',endDate:'2026-09-18',text:'',links:[]},{key:'2026-09-19',label:'Samedi',startDate:'2026-09-19',endDate:'2026-09-19',text:'',links:[]},{key:'2026-09-20',label:'Dimanche',startDate:'2026-09-20',endDate:'2026-09-20',text:'',links:[]}]},
{id:102,archangel:'Gabriel',year:'2026–2027',status:'planned',days:[{key:'preparation-gabriel',label:'Préparation',startDate:'',endDate:'',text:'',links:[]}]},
{id:103,archangel:'Raphaël',year:'2027',status:'planned',days:[{key:'preparation-raphael',label:'Préparation',startDate:'',endDate:'',text:'',links:[]}]},
{id:104,archangel:'Ouriel',year:'2028',status:'planned',days:[{key:'preparation-ouriel',label:'Préparation',startDate:'',endDate:'',text:'',links:[]}]}
],contents:[],events:[]};
function clone(v){return JSON.parse(JSON.stringify(v))}
function dateKey(){return 'day-'+Date.now()+'-'+Math.random().toString(36).slice(2,7)}
function daysBetween(start,end){if(!start||!end)return[];const out=[];let d=new Date(start+'T12:00:00'),e=new Date(end+'T12:00:00');while(d<=e){const key=d.toISOString().slice(0,10);out.push({key,date:key,label:d.toLocaleDateString('fr-FR',{weekday:'long'}),short:d.toLocaleDateString('fr-FR',{day:'numeric',month:'short'})});d.setDate(d.getDate()+1)}return out}
function daysFromLegacy(c){const out=[{key:'preparation',label:'Préparation',startDate:'',endDate:'',text:'',links:[]}];if(c.startDate&&c.endDate){for(const d of daysBetween(c.startDate,c.endDate)){out.push({key:d.key,label:d.label.charAt(0).toUpperCase()+d.label.slice(1),startDate:d.date,endDate:d.date,text:'',links:[]})}}return out}
function normalizeDay(d){const oldDate=d.date||'';return{key:d.key||oldDate||dateKey(),label:d.label||(!oldDate?'Jour':new Date(oldDate+'T12:00:00').toLocaleDateString('fr-FR',{weekday:'long'})),startDate:d.startDate||oldDate||'',endDate:d.endDate||d.startDate||oldDate||'',text:d.text||'',links:Array.isArray(d.links)?d.links.filter(x=>x&&x.url).map(x=>({label:x.label||x.url,url:x.url})):[]}}
function loadState(){let old=null;try{old=JSON.parse(localStorage.getItem('celebrations-state')||'null')}catch(e){};if(!old)return clone(DEFAULTS);const s={...clone(DEFAULTS),...old};s.groups=Array.isArray(s.groups)&&s.groups.length?s.groups:clone(DEFAULTS.groups);if(typeof s.groups[0]==='string')s.groups=s.groups.map((name,i)=>({id:i===0?'all':'group-'+i,name}));if(!s.groups.some(g=>g.id==='all'))s.groups.unshift({id:'all',name:'Tous'});s.categories=Array.isArray(s.categories)?s.categories:[...DEFAULTS.categories];['Images','Liens'].forEach(c=>{if(!s.categories.includes(c))s.categories.push(c)});s.celebrations=Array.isArray(s.celebrations)&&s.celebrations.length?s.celebrations:clone(DEFAULTS.celebrations);s.celebrations.forEach((c,i)=>{if(!c.id)c.id=1000+i;if(!c.archangel)c.archangel=(c.name||'').replace('Archange ','')||'Michaël';if(!Array.isArray(c.days)||!c.days.length)c.days=daysFromLegacy(c);c.days=c.days.map(normalizeDay);delete c.startDate;delete c.endDate});s.contents=Array.isArray(s.contents)?s.contents:[];s.events=Array.isArray(s.events)?s.events:(Array.isArray(s.program)?s.program.map(e=>({...e,celebrationId:e.celebrationId||101,dayKey:e.dayKey||e.date||'preparation'})):[]);if((old.version||0)<4){const demoNames=['Livret de préparation',"Chant d’ouverture",'Psaume de préparation',"Vidéo d’introduction"];const demoIds=s.contents.filter(c=>demoNames.includes(c.name)).map(c=>c.id);s.contents=s.contents.filter(c=>!demoNames.includes(c.name));const demoTitles=['Préparer la célébration','Ouverture de la célébration','Office du matin','Rendez-vous des Porteurs d’Ange','Enseignement','Célébration principale','Clôture de la célébration'];s.events=s.events.filter(e=>!demoTitles.includes(e.title));s.events.forEach(e=>e.contentIds=(e.contentIds||[]).filter(id=>!demoIds.includes(id)))}s.events.forEach(e=>{if(!e.celebrationId)e.celebrationId=101;const cel=s.celebrations.find(c=>c.id===e.celebrationId);if(!e.dayKey)e.dayKey=e.date||cel?.days?.[0]?.key||'preparation';if(cel&&!cel.days.some(d=>d.key===e.dayKey)){const match=cel.days.find(d=>d.startDate&&d.startDate===e.date);e.dayKey=match?.key||cel.days[0]?.key||'preparation'}if(!Array.isArray(e.contentIds))e.contentIds=[];delete e.date});if(!s.celebrations.some(c=>c.id===s.currentCelebrationId))s.currentCelebrationId=s.celebrations[0]?.id||null;if(!s.celebrations.some(c=>c.id===s.adminCelebrationId))s.adminCelebrationId=s.currentCelebrationId;if(!s.groups.some(g=>g.id===s.profile))s.profile='all';s.version=6;saveState(s);return s}
function saveState(s){localStorage.setItem('celebrations-state',JSON.stringify(s))}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function groupName(s,id){return s.groups.find(g=>g.id===id)?.name||'Tous'}
function formatDate(v,opts={day:'numeric',month:'long',year:'numeric'}){if(!v)return'';return new Date(v+'T12:00:00').toLocaleDateString('fr-FR',opts)}
function dayDateLabel(d){if(!d)return'';if(d.startDate&&d.endDate&&d.startDate!==d.endDate)return `${formatDate(d.startDate)} → ${formatDate(d.endDate)}`;if(d.startDate)return formatDate(d.startDate);return'Sans date'}
function celebrationRange(c){const starts=(c?.days||[]).map(d=>d.startDate).filter(Boolean).sort(),ends=(c?.days||[]).map(d=>d.endDate||d.startDate).filter(Boolean).sort();return starts.length?{start:starts[0],end:ends[ends.length-1]||starts[0]}:{start:'',end:''}}
function dayForEvent(c,e){return (c?.days||[]).find(d=>d.key===e.dayKey)||null}
function contentIcon(t){return t==='PDF'?'📄':t==='Audio'?'♫':t==='Vidéo'?'▶':t==='Texte'?'¶':t==='Image'?'🖼️':'↗'}
const MEDIA_DB='celebrations-media-v1',MEDIA_STORE='files';
function openMediaDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(MEDIA_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(MEDIA_STORE))r.result.createObjectStore(MEDIA_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putMedia(key,file){const db=await openMediaDB();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).put(file,String(key));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function getMedia(key){const db=await openMediaDB();return new Promise((resolve,reject)=>{const r=db.transaction(MEDIA_STORE,'readonly').objectStore(MEDIA_STORE).get(String(key));r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function deleteMedia(key){const db=await openMediaDB();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).delete(String(key));tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function openStoredFile(content,download=false){const file=await getMedia(content.id);if(!file){alert('Le fichier n’est pas disponible dans ce navigateur.');return}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;if(download)a.download=content.fileName||file.name||content.name;else a.target='_blank';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000)}
async function attachAudioPlayer(container,content){const file=await getMedia(content.id);if(!file){container.innerHTML='<span class="muted">Fichier audio indisponible sur cet appareil.</span>';return}const url=URL.createObjectURL(file);const audio=document.createElement('audio');audio.controls=true;audio.preload='metadata';audio.src=url;audio.style.width='100%';container.appendChild(audio)}